import { Product } from "./types";

export const sellingProducts = [
  {
    id: 1,
    name: "Chocolate",
    weight: "1250",
    price: "135",
    image: "/images/bestSelling/chocolate-sauce.webp",
  },
  {
    id: 2,
    name: "Caramel",
    weight: "1250",
    price: "135",
    image: "/images/bestSelling/caramel.webp",
  },
  {
    id: 3,
    name: "BlueBerry",
    weight: "1250",
    price: "135",
    image: "/images/bestSelling/BlueBerry.webp",
  },
  {
    id: 4,
    name: "Strawberry",
    weight: "1250",
    price: "135",
    image: "/images/bestSelling/strawberry-sauce.webp",
  },
  {
    id: 5,
    name: "Passion Fruit",
    weight: "1250",
    price: "135",
    image: "/images/bestSelling/passionFruit-sauce.webp",
  },
];
export const recipes = [
  {
    id: 1,
    title: "Cocktails & Mocktails",
    description: "Sweet fruit mocktails and crème",
    image: "/images/feature/Cocktails.webp",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: 3,
    title: "Milkshakes & Smoothies",
    description: "Smooth protein-rich blends",
    image: "/images/feature/milkShake.jpg",
    color: "from-amber-500 to-orange-600",
  },
  {
    id: 4,
    title: "Desserts & Ice Cream",
    description: "Delicious sweets tasty tops",
    image: "/images/feature/dessert.webp",
    color: "from-rose-500 to-pink-600",
  },
  {
    id: 5,
    title: "Baking & Pastry",
    description: "Tasty treat decorations",
    image: "/images/feature/Cake.webp",
    color: "from-orange-600 to-rose-600",
  },
];

export const pages = [
  "/images/catalog/1-Picsart-AiImageEnhancer.jpg",
  "/images/catalog/catalogue-D (1)_page-0002.jpg",
  "/images/catalog/catalogue-D (1)_page-0003.jpg",
  "/images/catalog/catalogue-D (1)_page-0004.jpg",
  "/images/catalog/catalogue-D (1)_page-0005.jpg",
  "/images/catalog/catalogue-D (1)_page-0006.jpg",
  "/images/catalog/catalogue-D (1)_page-0007.jpg",
];
export const products: Product[] = [
  {
    id: 8,
    name: "Chocolate Chill",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/chocolate.png",
    borderColor: "border-stone-400",
    flavor: "Chocolate",
  },
  {
    id: 9,
    name: "Caramel Swirl",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/caramel.jpeg",
    borderColor: "border-amber-400",
    flavor: "Caramel",
  },
  {
    id: 2,
    name: "Blueberry Dream",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/blueberry.jpeg",
    borderColor: "border-blue-400",
    flavor: "Blueberry",
  },
  {
    id: 3,
    name: "Raspberry Rush",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/raspberry.jpeg",
    borderColor: "border-pink-400",
    flavor: "Raspberry",
  },
  {
    id: 10,
    name: "Mixberry Blast",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/mixberry.jpeg",
    borderColor: "border-purple-400",
    flavor: "Mixberry",
  },
  {
    id: 1,
    name: "Strawberry Splash",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/strawberry.jpeg",
    borderColor: "border-red-400",
    flavor: "Strawberry",
  },
  {
    id: 11,
    name: "Mango Madness",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/mongo.jpeg",
    borderColor: "border-orange-500",
    flavor: "Mango",
  },
  {
    id: 5,
    name: "Pineapple Punch",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/pineapple.jpeg",
    borderColor: "border-yellow-400",
    flavor: "Pineapple",
  },
  {
    id: 4,
    name: "Peach Breeze",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/peach.jpeg",
    borderColor: "border-orange-400",
    flavor: "Peach",
  },
  {
    id: 6,
    name: "Kiwi Kick",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/kiwi.jpeg",
    borderColor: "border-green-400",
    flavor: "Kiwi",
  },
  {
    id: 7,
    name: "Passion Fruit Pop",
    brand: "Fresh Vibes",
    price: 135,
    image: "/images/products/passion_fruit.jpeg",
    borderColor: "border-yellow-500",
    flavor: "Passion Fruit",
  },
];
export const tel = Number("01050677740");
export const support = Number("01007006871");
export const gmail = "akulatopping@gmail.com";
export const facebook = "https://m.me/Akula Topping";
export const facebookMessages = "https://m.me/akulatopping";
